name: hbv_nano
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - snakemake-minimal=8.20.5
  - pip=24.2
  - pip:
    - biopython==1.84
    - pandas==2.2.3
    - click==8.1.3
    - boto3==1.35.29
    - vcfpy==0.13.8
  