# Folder with input .fastq files.
fastq_folder: "data/hbv_val_02"

# Output folder:
output: "output"

# Timestamp:
now_time: ""

# Apptainer images
fastp: "workflow/images/fastp_0.23.4.img"
freebayes: "workflow/images/freebayes_1.3.7.img"
medaka: "workflow/images/medaka_1.12.0.img"
minimap2: "workflow/images/minimap2_2.28.img"
samtools: "workflow/images/samtools_1.20.img"
